In [1]:
import numpy as np

### Vector & Matrix

In [2]:
vector = np.array([1,2,3])

print(vector)

matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[1 2 3]
[[1 2 3]
 [4 5 6]]


### Zeros & Ones & Full

In [3]:
np.zeros(4,dtype=int)

np.ones(4,dtype=float)

np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [4]:
np.eye(4) ## diagonal array of length n*n

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.seed(0)

arr1= np.random.randint(10,size=3) ### one dimentional 
arr2 = np.random.randint(25,size=(3,3)) ## two dimensional array 2 x 3 
arr1 = arr1 + 4

3

In [22]:
for i,j in range(arr2.size):
    print(arr2[i][j])

TypeError: cannot unpack non-iterable int object